### ISSUE TITLE
Quick update thank you

### ISSUE THREAD

**Issue by liyunfang** [dektrium/yii2-rbac#1]
Quick update thank you
Quick update thank you
Quick update thank you
Quick update thank you

**Comment by dmeroff** [comment]
What does this mean? :smiley:

**Comment by liyunfang** [comment]
Feel shy, I English not good. The meaning is: waiting for you to release a stable version, thank you.
Can you speak Chinese?

**Comment by dmeroff** [comment]
I'll do my best to release stable version as soon as possible.
No, I don't speak Chinese.

**Comment by abhi1693** [comment]
By when can we expect the release?

**Comment by dmeroff** [comment]
I'm too busy right now, so I don't know. Maybe in first weeks of February there will be implemented basic features.

**Comment by abhi1693** [comment]
Will it be compatible with your yii2-user module?

**Comment by dmeroff** [comment]
Yes, of course.
