### ISSUE TITLE
Assignment Management not possible

### ISSUE THREAD

**Issue by waza-ari** [dektrium/yii2-rbac#10]
When opening the route "rbac/assignment/assign&id=3", Yii2 fires an error:

`Setting unknown property: dektrium\rbac\widgets\Assignments::model`

Stack Trace:

```
1. in /var/www/html/hc/vendor/yiisoft/yii2/base/Component.php at line 197
2. in /var/www/html/hc/vendor/yiisoft/yii2/BaseYii.php – yii\base\Component::__set('model', dektrium\rbac\models\Assignment) at line 518
3. in /var/www/html/hc/vendor/yiisoft/yii2/base/Object.php – yii\BaseYii::configure(dektrium\rbac\widgets\Assignments, ['model' => dektrium\rbac\models\Assignment]) at line 105
4. yii\base\Object::__construct(['model' => dektrium\rbac\models\Assignment])
5. in /var/www/html/hc/vendor/yiisoft/yii2/di/Container.php – ReflectionClass::newInstanceArgs([['model' => dektrium\rbac\models\Assignment]]) at line 372
6. in /var/www/html/hc/vendor/yiisoft/yii2/di/Container.php – yii\di\Container::build('dektrium\rbac\widgets\Assignment...', [], ['model' => dektrium\rbac\models\Assignment]) at line 151
7. in /var/www/html/hc/vendor/yiisoft/yii2/BaseYii.php – yii\di\Container::get('dektrium\rbac\widgets\Assignment...', [], ['model' => dektrium\rbac\models\Assignment]) at line 344
8. in /var/www/html/hc/vendor/yiisoft/yii2/base/Widget.php – yii\BaseYii::createObject(['model' => dektrium\rbac\models\Assignment, 'class' => 'dektrium\rbac\widgets\Assignment...']) at line 96
9. in /var/www/html/hc/vendor/dektrium/yii2-rbac/controllers/AssignmentController.php – yii\base\Widget::widget(['model' => dektrium\rbac\models\Assignment]) at line 40
10. dektrium\rbac\controllers\AssignmentController::actionAssign('3')
11. in /var/www/html/hc/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array([dektrium\rbac\controllers\AssignmentController, 'actionAssign'], ['3']) at line 55
12. in /var/www/html/hc/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams(['r' => 'rbac/assignment/assign', 'id' => '3']) at line 151
13. in /var/www/html/hc/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction('assign', ['r' => 'rbac/assignment/assign', 'id' => '3']) at line 455
14. in /var/www/html/hc/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction('rbac/assignment/assign', ['r' => 'rbac/assignment/assign', 'id' => '3']) at line 84
15. in /var/www/html/hc/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest(yii\web\Request) at line 375
16. in /var/www/html/hc/web/index.php – yii\base\Application::run() at line 12
```

**Comment by dmeroff** [comment]
You should not open "rbac/assignment/assign" route. It is used only to get assignment form via ajax. Instead you should use Assignments widget in your user management form. Or if you are using yii2-user you can just edit assignments on user edit page.

**Comment by waza-ari** [comment]
Hi, i am using yii2-user and yii2-rbac, but on the user page there is no possibility to manage group assignments. Is there anything that need to be configured?

**Comment by dmeroff** [comment]
@waza-ari you don't need to configure anything, but just install yii2-user and yii2-rbac using composer. After that you will be able to manage assigned roles on user update page (/user/admin/update?id=)

**Comment by waza-ari** [comment]
@dmeroff I had both modules installed through composer. I however found the issue. yii2-user was included using the following line:

`"dektrium/yii2-user": "1.0.*@dev"`

Not sure what composer did, however for some reason, an old commit had been checked out. Changed the line to 0.9.4, did composer update and a more recent version was pulled, including the required modules for assignment management.

In my previous installation, the tabbed profile was not there, all options were simply shown in one page. Thats why I could not find the reference for assignment management in my local copy of the source..

Thanks for this great module, it is now working perfectly.

**Comment by ash-b** [comment]
i have installed both the modules through composer.but in user update i can not see assignment widget. i updated the coposer.phar but still no widget.

**Comment by rajaeIceberg** [comment]
i have the same issue i can not see assignement widget.

**Comment by rajaeIceberg** [comment]
it still in loading role and permissions for affectations
