### ISSUE TITLE
Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'

### ISSUE THREAD

**Issue by gaurishpatil** [dektrium/yii2-rbac#115]
$ php yii migrate/up --migrationPath=@yii/rbac/migrations
Yii Migration Tool (based on Yii v2.0.11.2)

Total 1 new migration to be applied:
        m140506_102106_rbac_init

Apply the above migration? (yes|no) [no]:yes
*** applying m140506_102106_rbac_init
Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'

in C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\rbac\migrations\m140506_102106_rbac_init.php:27

Stack trace:
#0 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\rbac\migrations\m140506_102106_rbac_init.php(45): m140506_102106_rbac_init->getAuthManager()
#1 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(654): m140506_102106_rbac_init->up()
#2 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(166): yii\console\controllers\BaseMigrateController->migrateUp('m140506_102106_...')
#3 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#4 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#5 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#6 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\console\Controller.php(128): yii\base\Controller->runAction('up', Array)
#7 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\base\Module.php(523): yii\console\Controller->runAction('up', Array)
#8 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
#9 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate/up', Array)
#10 C:\wamp64\www\Ubser-Web\vendor\yiisoft\yii2\base\Application.php(380): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 C:\wamp64\www\Ubser-Web\yii(20): yii\base\Application->run()
#12 {main}

**Comment by gaurishpatil** [comment]
solved, Updated web.php & console.php as,

```
'authManager'  => [
        'class'        => 'yii\rbac\DbManager',
   ],
```

**Comment by AdeSupriyadi** [comment]
I was set config/web.php 
'components' => [
...
'authManager' => [
            //'class' => 'yii\rbac\PhpManager',
            'class' => 'yii\rbac\DbManager',
        ],
...
]

but problem not solved

**Comment by eddjonson** [comment]
Solved add these lines in components section of config/web.php and config/console.php

'authManager'  => [
        'class'        => 'yii\rbac\DbManager',
   ],

**Comment by toir427** [comment]
I am using this link and this working for me try it too
https://stackoverflow.com/questions/30478903/yii2-cannot-perform-rbac-migration-you-should-configure-authmanager?rq=1
