### ISSUE TITLE
Unit tests 

### ISSUE THREAD

**Issue by gunmetal313** [dektrium/yii2-rbac#12]
Возможно ли использовать yii2-rbac отдельно от yii2-user?
И планируются ли unit тесты в yii2-rbac?

**Comment by dmeroff** [comment]
Да, возможно. Правда пока я не уверен, что так будет всегда.
Пока не знаю, здесь всё упирается в моё свободное время.
P.S. лучше такие вопросы писать в Gitter или мне на почту, Github Issues всё-таки не для этого.
P.P.S Лучше всё-таки на английском писать, давайте уважать всех пользователей.
