### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by zxczxc12** [dektrium/yii2-rbac#16]
1) When you delete a user to keep all the rights and permissions in RBAC
2) At the first appointment to the user permissions - everything is fine. Repeated - not deleted the old permit
3) In the list of permissions are displayed all the permissions after upgrading the user rights

1) При удалении юзера удалять все его права и разрешения в RBAC
2) При первом назначении юзеру разрешений - все нормально. При повторном - не удаляются старые разрешения 
3) В списке разрешений не показываются все разрешения после обновления прав юзеру

**Comment by baiano** [comment]
Hey, sup?
Take a look on https://github.com/dektrium/yii2-rbac/pull/15 and see if it will helps you. 

C ya

**Comment by zxczxc12** [comment]
Yes , it is all i need.
But i don't understand, when this bugfix will be commited to main code ?

**Comment by baiano** [comment]
Well, i dont know if it will be merged on main code, since its still a Pull request and i'm not related to yii2-rbac development. By the way, i think that #15 is not the best way to fix it, but at least its working.

**Comment by dmeroff** [comment]
2, 3 - fixed,
1 - I'll add this as soon as possible.
