### ISSUE TITLE
No migrations folder ?

### ISSUE THREAD

**Issue by Quexer69** [dektrium/yii2-rbac#2]
`$ php yii migrate/up --migrationPath=@vendor/dektrium/yii2-rbac/migrations`

**Comment by missjewel** [comment]
this line not working : php yii migrate/up --migrationPath=@vendor/dektrium/yii2-rbac/migrations.

Error migration failed. Directory specified migrationPath doesn't exist.

**Comment by dmeroff** [comment]
Yes, migration folder is missing, but it does not matter at the moment, because there are no migrations at all. BTW I'll fix this asap.

**Comment by jsobers1331** [comment]
Was just coming to report this.... Good to know you're on it.

**Comment by dmeroff** [comment]
Fixed.

**Comment by arogachev** [comment]
There are no files except `.gitkeep` still. https://github.com/dektrium/yii2-rbac/tree/master/migrations

**Comment by arogachev** [comment]
Got it, it's located under `vendor/yiisofy/yii2/rbac/migrations` folder.
