### ISSUE TITLE
Not redirecting after update

### ISSUE THREAD

**Issue by loveorigami** [dektrium/yii2-rbac#20]
Здравствуйте, Дмитрий.
Установил данный модуль вместе с yii2-user.

При создании или редактировании роли, правила.... не происходит редиректа.
В консоли получаю ответ
![rbacerror](https://cloud.githubusercontent.com/assets/98164/8019559/d0e92e26-0c5d-11e5-9de5-3501f9876efa.jpg)

Нашел, в чем причина:
Если закомментировать - https://github.com/dektrium/yii2-rbac/blob/master/models/AuthItem.php#L129
и
https://github.com/dektrium/yii2-rbac/blob/master/models/AuthItem.php#L132
```php
        if ($isNewItem) {
            //\Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been created'));
            $this->manager->add($this->item);
        } else {
           // \Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been updated'));
            $this->manager->update($oldName, $this->item);
        }
```
тогда все сохраняется и редирект происходит.

попробовал отключить в конфиге флеш-сообщения
```php
    'modules' => [
        'rbac' => [
            'class' => 'dektrium\rbac\Module',
            'enableFlashMessages' => false,
            'admins'=>['webmaster'],
        ],
    ],
```
результата не дало.

**Comment by thiagotalma** [comment]
You are not in a Russian site.
If I write in Brazilian Portuguese you understand? 

http://translate.google.com

**Comment by loveorigami** [comment]
@thiagotalma sorry, I am write for Dmitry from Russia. 
About my issue - I can't redirecting after update role.
If comment 
```php
        if ($isNewItem) {
            //\Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been created'));
            $this->manager->add($this->item);
        } else {
           // \Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been updated'));
            $this->manager->update($oldName, $this->item);
        }
``` 
redirect after update is good.

**Comment by thiagotalma** [comment]
Here you send a message to a collective of people.

Not always Dmitry is available to help you in the time you need, then others, like me, will try to help you and allow Dmitry can have more time to develop the project.

Writing in Russian, hardly anyone will try to help you.

I am Brazilian, I can not read/write English, but translate is my friend  :wink:

**Comment by dmeroff** [comment]
You probably have some problem with sessions. I've never met such issue, so I probably won't be able to help you and you have to find solution yourself.

**Comment by loveorigami** [comment]
Many thanks for answer/ Perhaps you're right.

But as it works off 'enableFlashMessages' => false,
In the code, I see - that FlashMessages work is always.

And in my admin-module are displayed twice.
