### ISSUE TITLE
Roles and permissions

### ISSUE THREAD

**Issue by loveorigami** [dektrium/yii2-rbac#21]
Another point:
Create a hierarchy of access roles.

* Root
* Admin
*  Editor
*  User

Roles Root awarded child-> Admin
I go to the Admin. Among the available childs listed root.

```ru
Еще один момент:
Создаю иерархию ролей доступа.
* Root
* Admin
* Editor
* User

Роли Root присвоил child-> Admin
Захожу в Admin. Среди доступных childs значится root.
```

![children](https://cloud.githubusercontent.com/assets/98164/8019631/c58e35d2-0c60-11e5-977e-f129890623c9.jpg)

And have error
![errr](https://cloud.githubusercontent.com/assets/98164/8019641/0a6be712-0c61-11e5-9198-75047b437137.jpg)
in the list of children placed only roles, no one has not heritable, and to exclude those who have this role is listed as child throughout the hierarchy ...

User for editing everything above it (editor, admin, root) are not shown in the list ...

Also, permissions - do not show in the list of those who have already inherited the previous role.

For example yii-rights, it looks like. I edit the role of editor (as admin, root in the list lack)
```ru
т..е напрашивается в список детей помещать только те роли, никем еще не наследуемы, и исключать те, у которых данная роль значится, как child по всей иерархии...

т..е при редактировании User все, что выше него (editor, admin, root) в списке не показываются...

Также и с разрешениями - не показывать в списке те, которые уже унаследованы предыдущей ролью.

На примере yii-rights это выглядит так. Редактирую роль editor (роли admin, root в списке отсутсвуют)
```
![roles](https://cloud.githubusercontent.com/assets/98164/8019655/ca742952-0c61-11e5-978e-3e15d84fd457.jpg)

**Comment by loveorigami** [comment]
@thiagotalma adding en translate.

**Comment by dmeroff** [comment]
I'll try to fix asap.

**Comment by dmeroff** [comment]
Fixed!
