### ISSUE TITLE
Create pre-release 0.1.0

### ISSUE THREAD

**Issue by schmunk42** [dektrium/yii2-rbac#22]
How about adding a 0.1.0, so we could stability stable in composer.json.
It also helps in keeping apps stable and composer updates fast.

You can still change anything during 0.x - according to semver.

**Comment by dmeroff** [comment]
Good idea, I'll do it tomorrow.

**Comment by dmeroff** [comment]
Done. Sorry for the delay with this.

**Comment by schmunk42** [comment]
@dmeroff Time for another one? :)

**Comment by dmeroff** [comment]
@schmunk42  Yes, I'll add it in a few days.

**Comment by dmeroff** [comment]
Added pre-release 0.2.0.
