### ISSUE TITLE
Ошибка при миграции/Добавить в документацию по установке

### ISSUE THREAD

**Issue by martrix78** [dektrium/yii2-rbac#23]
Может стоит в мануал по установке добавить что в config/console надо прописать
	'components' => [
                'authManager' => [
                    'class' => 'yii\rbac\DbManager',
                ],  
...
?

**Comment by dmeroff** [comment]
Please, write in english in feature. I'll handle this documentation issue tomorrow.

**Comment by WeslomPo** [comment]
I think you forget for that issue.
