### ISSUE TITLE
Missing Migration File

### ISSUE THREAD

**Issue by apickstock** [dektrium/yii2-rbac#26]
Doesn't appear to be any migration file to create database tables and entries.

No new migration found. Your system is up-to-date. when attempting install.

**Comment by dmeroff** [comment]
Which command do you use to apply migraitons?

**Comment by apickstock** [comment]
using 
yii migrate/up --migrationPath=@yii/rbac/migrations

**Comment by dmeroff** [comment]
It seems that you already applied needed migration. Check if tables `auth_*` exist? If so then it is ok. If not, you should look up in migrations table and remove the row with name `m140506_102106_rbac_init`.
