### ISSUE TITLE
Unable to delete Permissions

### ISSUE THREAD

**Issue by jsobers1331** [dektrium/yii2-rbac#3]
Added one test Permission to test the entry of this and see how it works and noticed when I pressed the delete button i would get a "Not Found (#404)"

Information from Log:

exception 'yii\web\NotFoundHttpException' in C:\xampp\htdocs\[Yii2Project]\vendor\dektrium\yii2-rbac\controllers\RoleController.php:37

Stack trace:
#0 C:\xampp\htdocs\[Yii2Project]\vendor\dektrium\yii2-rbac\controllers\ItemControllerAbstract.php(130): dektrium\rbac\controllers\RoleController->getItem('Blog')
#1 [internal function]: dektrium\rbac\controllers\ItemControllerAbstract->actionDelete('Blog')
#2 C:\xampp\htdocs\[Yii2Project]\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\[Yii2Project]\vendor\yiisoft\yii2\base\Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\[Yii2Project]\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('delete', Array)
#5 C:\xampp\htdocs\[Yii2Project]\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('rbac/role/delet...', Array)
#6 C:\xampp\htdocs\[Yii2Project]\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 C:\xampp\htdocs\[Yii2Project]\backend\web\index.php(18): yii\base\Application->run()
#8 {main} 

Note:
I'm using the Yii v2.0.4-dev

**Comment by dmeroff** [comment]
Fixed.
