### ISSUE TITLE
Integration with yii2-user

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-rbac#47]
Currently when Yii2-user is installed the integration of admins is done as folllows:

            if ($this->checkUserModuleInstalled($app)) {
                $app->getModule('rbac')->admins = $app->getModule('user')->admins;
            }   

However, yii2-user uses User::getIsAdmin everywhere (which checks if the user is in array mentioned above). 
In Yii2-user I can overwrite the getIsAdmin function to properly use a role instead. However then yii2-rbac itself does not respect that and still needs a hardcoded admin array configuration.

Suggestion: if we have the yii2-user module use ->getIsAdmin instead.

**Comment by dmeroff** [comment]
Thank you, I merged your pull-request.
