### ISSUE TITLE
Match filter in AuthItem is too restrictive

### ISSUE THREAD

**Issue by jacmoe** [dektrium/yii2-rbac#49]
I can't enter `project.create` as a permission name, and that bothers me :)

The regex is too restrictive.

Maybe this:

~~~
^[a-z0-9]{2}[a-z0-9.]{0,}[a-z0-9]{1}+$
~~~

Source: http://stackoverflow.com/questions/29881823/php-preg-match-only-numbers-letters-and-dot

The reason why this is important is because when I use Yii rbac console command to create rules, like project.create, project.delete, etc - then I can't edit them in the Rbac admin section because Yii2-rbac module tells me that the names are invalid. :)

**Comment by jacmoe** [comment]
I could probably override the model, but I believe that this should be fixed in your otherwise excellent module. :)

**Comment by jacmoe** [comment]
The offending line of code is:
~~~
            ['name', 'match', 'pattern' => '/^[\w-]+$/'],
~~~
Just in case you were wondering

**Comment by jacmoe** [comment]
See #50

**Comment by dmeroff** [comment]
Thank you!
