### ISSUE TITLE
Tag v0.2.0 should be 0.2.0

### ISSUE THREAD

**Issue by schmunk42** [dektrium/yii2-rbac#52]
We stumbled upon this issue https://github.com/dmstr/yii2-cms-metapackage/issues/1

I think `v0.2.0` should be `0.2.0` or do you plan to release all future version with a `v` prefix, which is not very common. 

You may keep the `v0.2.0` for backward-compatibitly.

**Comment by schmunk42** [comment]
Just FYI, the `v` prefix does not cause the error, I just noticed that while investigating the issue linked above.

**Comment by dmeroff** [comment]
I've started naming new versions without `v` prefix, since it does not make any sense. Check out 0.3.0 release.
