### ISSUE TITLE
Error for dev-master

### ISSUE THREAD

**Issue by habib-royni-mujtahid** [dektrium/yii2-rbac#53]
I want to install rbac extension but when composer update i always found error like this.

[RuntimeException]                                                                                                                                                   
  The .git directory is missing from /home/.../webapp/oil-palm-cultivation-thesis/vendor/dektrium/yii2-rbac, see https://getcomposer.org/commit-deps for more information

Please fix this bug. TY.

**Comment by dmeroff** [comment]
Actually, this is not a problem with yii2-rbac. Try removing yii2-rbac and then installing it again,
