### ISSUE TITLE
Create Permission or Role problem

### ISSUE THREAD

**Issue by nsaliu** [dektrium/yii2-rbac#57]
Hi,
I've installed this extension in combination with yii2-users, and it's cool.
But in Admin section, when I try to create a Permission or Role, there is a problem that I can't understand.

I've attach images to explain.
**How do I fix it?**

Thanks.

<img width="1246" alt="schermata 2016-02-21 alle 19 21 47" src="https://cloud.githubusercontent.com/assets/2877876/13204442/682e4f20-d8d0-11e5-8dc9-70ea05a4258a.png">

<img width="1181" alt="schermata 2016-02-21 alle 19 22 46" src="https://cloud.githubusercontent.com/assets/2877876/13204450/96a53e4a-d8d0-11e5-90da-d36589af5073.png">

**Comment by dmeroff** [comment]
You have to fill that field with a fullname of a rule class (e.g. \app\rules\MyRule)
