### ISSUE TITLE
Permissions Rule Class does not update

### ISSUE THREAD

**Issue by thecortex** [dektrium/yii2-rbac#59]
Hello,

I tried updating a permission in 
http://local.mydomain.com/backend/rbac/permission/update?name=updateOwnPlace

However, the Rule field, is never updated, and I still get success message after clicking save.
Rule: common\rbac\rules\PlaceOwnerRule

Thanks~

**Comment by shahidt** [comment]
I have this same problem too. Could you resolve this?

**Comment by shahidt** [comment]
To add more info. I did a server reset and logged out and logged in again. Then I was able to add the rule.

**Comment by thecortex** [comment]
I should try it and feed you back

**Comment by dmeroff** [comment]
I cannot reproduce this. Could you please provide more information on how to reproduce it (yii2 version, yii2-rbac version, steps to reproduce).

**Comment by thecortex** [comment]
Dear Dmitry,

Thank you, but I can't generate the issue again. It seems to be solved. I guess it was related to a problem with my own files that was solved by running 
$ composer install

With kind regards,

**Comment by dmeroff** [comment]
Ok, then i'm closing this issue.
