### ISSUE TITLE
How to use this extension?

### ISSUE THREAD

**Issue by gitowiec** [dektrium/yii2-rbac#70]
Hi
I am new to Yii, I am writing simple application, and I found dektrium/yii2-rbac extension is perfect for it.
I managed to install it and add roles and permissions, but I don't know how to use it in controllers, eg. block users from accessing actions from controllers. Please provide an example in README.md . Best regards

**Comment by dmeroff** [comment]
Yii2-rbac is used to create RBAC data and in order to use it in your code you should use methods provided by Yii. You can read more in [documentation](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html).
