### ISSUE TITLE
Allow user to set data when creating auth items.

### ISSUE THREAD

**Issue by SamMousa** [dektrium/yii2-rbac#71]
Is there a reason we cannot set the auth items' data when creating it via the GUI?

Would be nice if we can enter data, for example in JSON format. The controller could then decode it and pass it on to Yii which would serialize it when saving to the database.

In case an object is unserialized from the database (in case of updates), a message could be shown that this item does not use a "simple" PHP array and editing for objects is not supported.

**Comment by dmeroff** [comment]
Cool idea, I'll definitely implement this, but I don't think it will be implemented until end of June.

**Comment by dmeroff** [comment]
Done!
