### ISSUE TITLE
AccessControl for routes (permissions with "/" as prefix)

### ISSUE THREAD

**Issue by jkmssoft** [dektrium/yii2-rbac#76]
With a AccessControl component access to routes could be easily restricted.

Permissions with "/" as prefix could be used to test if a user has access to a specifc route.

Usage:
`````php
    'as access' => [
        'class' => 'dektrium\rbac\components\AccessControl',
        'allowRoutes' => [
            '/debug/default/toolbar',
            '/debug/default/view',
            '/debug/*',
        ],
    ],
````

I'll try to implement this in the next few weeks/months.

**Comment by dmeroff** [comment]
I don't understand how does this differ from `yii\filters\AccessControl`?

**Comment by jkmssoft** [comment]
Sorry, I don't have much experience with Yii.

With `yii\filters\AccessControl` I can restrict access to routes (actionXY) by using rbac permissions?

**Comment by dmeroff** [comment]
Yes, you can.

```php
'accessControl' => [
    'class' => 'yii\filters\AccessControl',
    'rules' => [
        [
            'allow' => true,
            'actions' => ['create'], // <-- action name
            'roles' => ['createPost'], // <-- permission name
        ],
        [
            'allow' => true,
            'actions' => ['delete'],  // <-- action name
            'roles' => ['deletePost'], // <-- permission name
        ],
    ],
],
```

**Comment by bizilliam** [comment]
I had a similar issue.  Initially routes or 'auth_items' were created '/route/*' for example.  yii2-rbac had this as invalid in the model.  I changed models\AuthItem:

`['name', 'match', 'pattern' => '/^[\w][\w-.:]+[\w]$/'],`
to
`['name', 'match', 'pattern' => '/^.[\w][\w-.:]+[\w]$/'],`

to allow creation/editing of the /path/ permissions.

Speaking of, I have a question dmeroff:  I have some users that need access to /user/admin/* , but not /rbac/*  .  I hide this in the menus  like:

`'visible' => (isset(Yii::$app->extensions['dektrium/yii2-rbac']) && Yii::$app->user->can('sysadmin')),`

Regardless of what I have in 'auth_item', the adminPermission name always allows access to both.  Do I have to use AccessControl to over-ride RBAC/user permissions?  I need a sysadmin (allows access to create/edit users) and an rbacadmin (allows access to users and allows controls to create permissions/roles).

Thanks!

- Bill

**Comment by bizilliam** [comment]
As an update here.  allow one user 'sysadmin' to allow access to /user/ routes, but allow a second user 'rbacadmin' allow access to only /rbac/ routes, I did the following.

Set the adminPermission to 'sysadmin'.  Initially, this allows sysadmin to do rbac controls.  Then, changed:
yii2-rbac\Modules.Php:
from
```
                   [
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => [$this, 'checkAccess'],
                    ]
```
to
```
                   [
                        'allow' => true,
                        'actions' => ['index', 'update', 'delete', 'create'],
                        'roles' => ['rbacadmin'],
                    ]
```

Thanks all.
