### ISSUE TITLE
Integrity violation constraint in models\AuthItem.php

### ISSUE THREAD

**Issue by techie42** [dektrium/yii2-rbac#78]
When using the RBAC manager to create a new permission, an integrity constraint violation arises due to some change in the way rule data is added, when the rule field on the standard form is not set.  This only seems to have occurred in the last couple of days.

A temporary fix is as follows. Around line 171 (highlighted below), change the line to read:

`	    $this->item->ruleName    = strlen( trim( $this->rule ) ) > 0 ? $this->rule : null;
`

I haven't used rules thus far, so I don't know if this will impact on any other features down the line, but this single-line change resolves my issue.

`        $this->item->name        = $this->name;
        $this->item->description = $this->description;
        $this->item->data        = $this->data == null ? null : Json::decode($this->data);
        **$this->item->ruleName    = $this->rule;  <- CHANGE THIS LINE**
  
        if ($isNewItem) {
            \Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been created'));
            $this->manager->add($this->item);
        } else {
            \Yii::$app->session->setFlash('success', \Yii::t('rbac', 'Item has been updated'));
            $this->manager->update($oldName, $this->item);
        }`

After the single-line change, I can successfully create new permissions.

**Comment by dmeroff** [comment]
Fixed!
Thank you for reporting.
