### ISSUE TITLE
Update Installation Config 

### ISSUE THREAD

**Issue by jsobers1331** [dektrium/yii2-rbac#79]
https://github.com/dektrium/yii2-rbac/blob/master/docs/installation.md#step-2-configure-your-application

Step 2 configuration no longer works.

I noticed the recent changes, can you update the instructions so i know i placed the correct file for the config.

**Comment by onlytalk** [comment]
I have a same problem :(

**Comment by jsobers1331** [comment]
@onlytalk To fix my problem I used the following:

```
'rbac' => [
                 'class' => 'dektrium\rbac\RbacConsoleModule',
        ],
```

But lookout for the updated requirements for my method may not be completed correctly.

**Comment by onlytalk** [comment]
don't know...
`php yii migrate/up --migrationPath=@yii/rbac/migrations`
still not working (

**Comment by jsobers1331** [comment]
it won't work until you update your config with what i showed you above.

Please i don't see any migration updates either.

**Comment by onlytalk** [comment]
> D:\basic>php yii migrate/up --migrationPath=@yii/rbac/migrations
> Yii Migration Tool (based on Yii v2.0.9)
> 
> Total 1 new migration to be applied:
>         m140506_102106_rbac_init
> 
> Apply the above migration? (yes|no) [no]:y
> *** applying m140506_102106_rbac_init
> Exception 'yii\base\InvalidConfigException' with message 'You should configure "authManager" component to use database before executing this migration.'
> 
> in D:\basic\vendor\yiisoft\yii2\rbac\migrations\m140506_102106_rbac_init.php:27
> 
> Stack trace:
> #0 D:\basic\vendor\yiisoft\yii2\rbac\migrations\m140506_102106_rbac_init.php(45): m140506_102106_rbac_init->getAuthManager()
> #1 D:\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m140506_102106_rbac_init->up()
> #2 D:\basic\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m140506_102106_...')
> #3 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
> #4 D:\basic\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
> #5 D:\basic\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
> #6 D:\basic\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
> #7 D:\basic\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
> #8 D:\basic\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate/up', Array)
> #9 D:\basic\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate/up', Array)
> #10 D:\basic\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
> #11 D:\basic\yii(20): yii\base\Application->run()
> #12 {main}

**Comment by jsobers1331** [comment]
Oh you're now applying it for the first time. Thought you had it installed before.

Be sure you have in your config:

```php
'components' => [
    ...
    'authManager' => [
        'class' => 'dektrium\rbac\components\DbManager',
    ],
    ...
],
...
```

**Comment by onlytalk** [comment]
> 'components' => [
>         'request' => [
>             // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
>             'cookieValidationKey' => '',
>         ],
>         'cache' => [
>             'class' => 'yii\caching\FileCache',
>         ],
>         'errorHandler' => [
>             'errorAction' => 'site/error',
>         ],
>         'mailer' => [
>             'class' => 'yii\swiftmailer\Mailer',
>             // send all mails to a file by default. You have to set
>             // 'useFileTransport' to false and configure a transport
>             // for the mailer to send real emails.
>             'useFileTransport' => true,
>         ],
>         'log' => [
>             'traceLevel' => YII_DEBUG ? 3 : 0,
>             'targets' => [
>                 [
>                     'class' => 'yii\log\FileTarget',
>                     'levels' => ['error', 'warning'],
>                 ],
>             ],
>         ],
>         'db' => require(__DIR__ . '/db.php'),
>         'urlManager' => [
>             'enablePrettyUrl' => true,
>             'showScriptName' => false,
>             'rules' => [
>             ],
>         ],
>         'authManager' => [
>             'class' => 'dektrium\rbac\components\DbManager',
>         ],
>     ],

**Comment by dmeroff** [comment]
Guide has been updated.

**Comment by onlytalk** [comment]
Thank you!
