### ISSUE TITLE
Fatal error when run any yii  console command.

### ISSUE THREAD

**Issue by soap** [dektrium/yii2-rbac#80]
When I run yii migrate/history on console terminal. The following error shown.

`Exception 'yii\base\UnknownPropertyException' with message 'Setting unknown property: dektrium\rbac\RbacConsoleModule::admins'`

I look in RbacConsoleModule.php, it did not have admins property. So I modified method bootstrap($app) in Bootstrap.php  

```
            // if dektrium/user extension is installed, copy admin list from there
            if ($this->checkUserModuleInstalled($app) && ($app instanceof WebApplication)) {
                $app->getModule('rbac')->admins = $app->getModule('user')->admins;
            }
```
Then it works again.

My environments is on PHP 5.6 on Windows, Yii 2.0.5, yii2-rbac : dev-master 6998d19.

**Comment by dmeroff** [comment]
Fixed!
