### ISSUE TITLE
RBAC Migration need to config authManager in yii2 advanced

### ISSUE THREAD

**Issue by jberall** [dektrium/yii2-rbac#85]
When using the Yii2 Advanced it says in the https://github.com/dektrium/yii2-rbac/blob/master/docs/installation.md 
Under Installation:
NOTE: Please make sure that you don't have authManager component configured. It will be configured automatically during installation.
When running the migration I got the error:
Exception: Yii/base/invalidConfigException

The solution is to put the following 
    'components' => [
***
        'authManager' => [
            'class' => 'dektrium\rbac\components\DbManager',
        ],
***
],

### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version     2.0.9 |
| Yii2-rbac version off last commit  b4c4053 |
| PHP version      5.6.8 |

**Comment by dmeroff** [comment]
If you are using latest code from master branch and installed Yii2-rbac using composer then it should work without any problem.

**Comment by exneval** [comment]
@dmeroff 
Sorry but I still faced the same issue even with latest code from master branch,
And there's no documentation about yii2-advanced-app, should I put 
`'rbac' => 'dektrium\rbac\RbacWebModule',`
and
`'rbac' => 'dektrium\rbac\RbacConsoleModule',`

in `common/config/main.php`?

**Comment by jiitendrayadav** [comment]
Forbidden (#403) 

You are not allowed to perform this action.

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. 

common/config/main.php

'module'=>[
 'rbac' => 'dektrium\rbac\RbacWebModule',
]

and 

'module'=>[
 'rbac' => 'dektrium\rbac\RbacConsoleModule',
]

Try both but same issue occurred  

Thank you.

**Comment by tkutru** [comment]
The problem is caused by is initial [access check](https://github.com/dektrium/yii2-rbac/blob/master/RbacWebModule.php#L59)
```
    public function checkAccess()
    {
        $user = \Yii::$app->user->identity;
        if (method_exists($user, 'getIsAdmin')) {
            return $user->getIsAdmin();
        } else if ($this->adminPermission) {
            return $this->adminPermission ? \Yii::$app->user->can($this->adminPermission) : false;
        } else {
            return isset($user->username) ? in_array($user->username, $this->admins) : false;
        }
    }
```
You can quickly overcome this problem by implementing method getIsAdmin for your User model. When it returns true, you will be able to log into CRUD interface.
