### ISSUE TITLE
Yii2 Advanced config / common setup Documentation error

### ISSUE THREAD

**Issue by jberall** [dektrium/yii2-rbac#86]
The 'rbac' => 'dektrium\rbac\RbacWebModule',
should be 'rbac' => 'dektrium\rbac\Module',

| Q                 | A
| ----------------- | ---
| Yii2 version      |
| Yii2-rbac version |
| PHP version       |

**Comment by mtangoo** [comment]
Right! the first one is wrong

**Comment by dmeroff** [comment]
Not an issue.
You're using different versions of code and documentation.
Master branch code does not have `dektrium\rbac\Module` class anymore.
If you're using Yii2-rbac 0.3.0 (where class `dektrium\rbac\Module` exists) then you should follow [this docs](https://github.com/dektrium/yii2-rbac/blob/0.3.0/docs/README.md)

P.S. Please answer the questions about yii2 and yii2-rbac versions given in issue template in future.

**Comment by mtangoo** [comment]
:+1:
