### ISSUE TITLE
rbac and composer

### ISSUE THREAD

**Issue by lijan** [dektrium/yii2-rbac#87]
When you are using composer to install the yii2-rbac package you have missed RbacConsoleModule.php, RbacWebModule.php and commands folder. But instead you have Module.php file.
That lead to errors when running app such as:
`Exception 'ReflectionException' with message 'Class dektrium\rbac\RbacConsoleModule does not exist'`

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.9
| Composer  version      | 1.1.0
| Yii2-rbac version | 0.3
| PHP version       |  5.6

**Comment by dmeroff** [comment]
Yii2-rbac 0.3.0 does not have `dektrium\rbac\RbacConsoleModule` class. You probably using documentation for version 1.0.0-dev which is located in master branch.

If you're using version 0.3.0 then you should use [this](https://github.com/dektrium/yii2-rbac/tree/0.3.0/docs) documentation.

**Comment by lijan** [comment]
Sorry, thats my fault. 
But it will be nice if you will drop some lines in docs about installing module via composer. Just change the `composer install dektrium/yii2-rbac` to `composer require "dektrium/yii2-rbac:@dev"`
