### ISSUE TITLE
yii2-rbac updates broke console commands

### ISSUE THREAD

**Issue by bizilliam** [dektrium/yii2-rbac#89]
### What steps will reproduce the problem?
After a composer update of yii2-rbac, it appears that console commands no longer work.  Any console command ends up in error.  I can't for the life of me find any configurations that help fix problem.  Running yii2-advanced template.

common\config\main.php - 

`      example: components => [
          'authManager' => [
              'class' => 'yii\rbac\Dbmanager',
          ],
        ],`
`php yii migrate/up --migrationPath=@yii/rbac/migrations`
or
`php yii`

### What is the expected result?

`php yii` usually prints out help/use message.

### What do you get instead?
`Exception 'yii\base\InvalidConfigException' with message 'You have wrong authManager configuration'

in /var/www/vendor/dektrium/yii2-rbac/Bootstrap.php:48

Stack trace:
#0 /var/www/vendor/yiisoft/yii2/base/Application.php(291): dektrium\rbac\Bootstrap->bootstrap(Object(yii\console\Application))
#1 /var/www/vendor/yiisoft/yii2/base/Application.php(267): yii\base\Application->bootstrap()
#2 /var/www/vendor/yiisoft/yii2/console/Application.php(124): yii\base\Application->init()
#3 /var/www/vendor/yiisoft/yii2/base/Object.php(107): yii\console\Application->init()
#4 /var/www/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#5 /var/www/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#6 /var/www/yii(26): yii\console\Application->__construct(Array)
#7 {main}`
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      |  2.0.9
| Yii2-rbac version | dev-master b4c4053
| Yii2-user version | dev-master 9398573
| PHP version       |  5.6

**Comment by bizilliam** [comment]
If I comment out the throw line 48 from Bootstrap.php
`//                throw new InvalidConfigException('You have wrong authManager configuration');`

all works fine.

**Comment by dmeroff** [comment]
`authManager` should be instance of `dektrium\rbac\components\DbManager`, however in your configuration it is `yii\rbac\DbManager`.
You should either change it, or remove completely (but you need to configure console module as said in installation guide)
