### ISSUE TITLE
access control 

### ISSUE THREAD

**Issue by onward-web** [dektrium/yii2-rbac#92]
I do not understand the logic module 

How I can use the module to achieve blocking of access for a group user of action ?
Example:
Admin: have all privileges
Manager: have an privileges for action post/view, post/create, post/update
Guest: have an privileges for form action post/view

In module mdmsoft/yii2-admin I can do it 
https://github.com/mdmsoft/yii2-admin/blob/master/components/AccessControl.php

But, after install your module, Route(action) is opened, and any guest can do anything.

I need to write a custom class AccessControl, or add in behaviors rules ? 

I would like to use that your module, but I have a misunderstanding with him, please tell me.

**Comment by andrea82** [comment]
Hi, i'd like to have a global behavior for access control, but it's seem doesn't work.
I'added this code on backend config but nothing..
   'as beforeRequest' => [
class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                    'matchCallback' => function(){
                        $action = Yii::$app->controller->action->id;
                        $controller = Yii::$app->controller->id;
                        $route = $controller.'/'.$action;
                        if(Yii::$app->user->can($route))
                            return true;
                    }
                ],
            ],
]

there is a way to have access control behavior globally?
thanks.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
